CXX = g++

CXXFLAGS = -c -g -Wall -std=c++17

PROGRAM = Assignment5

CPPFILES = main.cpp NewImp.cpp

build:
	$(CXX) $(CXXFLAGS) $(CPPFILES)
	$(CXX) -o $(PROGRAM) *.o

clean:
	rm *.o Assignment5
	rm *.h.gch
