CXX = g++

CXXFLAGS = -c -g -Wall -std=c++17

PROGRAM = ElevatorSim
#ElevatorSim
CPPFILES = Assignment1.cpp Elevator.cpp



build:
	$(CXX) $(CXXFLAGS) $(CPPFILES)
	$(CXX) -o $(PROGRAM) *.o

clean:
	rm *.o ElevatorSim

